VB-1815, added word-break to all govuk-table cells, to fix long string issue
ministryofjustice/book-a-prison-visit-staff-ui pull request #489
Opened 2023-02-07 16:14 UTC by hutcheonb-moj

## Description
On active alerts, when a long string with no spaces had been added in comments, the string continued across the page, breaking out of its box and pushing all other content right, introducing side scrolling.

This fix adds word-break to all govuk-table cells, making all content stay within it's pre-defined location on the page.

2023-02-07 16:26 UTC, psoleckimoj commented on assets/sass/local.scss
> +}
Looks good, just need a newline leaving at the end of the file 👍

2023-02-07 16:28 UTC, psoleckimoj submitted a review, later dismissed
LGTM!

2023-02-10 08:22 UTC, tpmcgowan requested changes
I think this needs tweaking so it doesn't cause 'real' words to break in other cells (see comment with screenshot)

2023-02-10 08:22 UTC, tpmcgowan commented on assets/sass/local.scss
> + overflow-wrap: anywhere;
Tried this out locally and it's causing words to break mid-way through where it shouldn't happen (see screenshot). Depends a lot on window size so you don't always see it. Might need to be more targeted to the specific columns/cells likely to contain this kind of data?


![Screenshot 2023-02-10 at 08 10 40](https://user-images.githubusercontent.com/1441286/218038755-9bd1bbf3-8c12-45a0-86f4-e8284d06e1dc.png)

2023-02-10 14:14 UTC, tpmcgowan approved these changes
LGTM!

2023-02-10 14:35 UTC, merged